---
language: python
python: "3.7"

sudo: false

addons:
  apt:
    packages:
      - python-pip

install:
  - pip install ansible ansible-lint yamllint
  - ansible --version

before_script:
  - mkdir -p tests/roles/nginx_with_vhosts
  - cp -R tasks tests/roles/nginx_with_vhosts/

script:
  - ansible-lint .
  - yamllint .
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
