---

- name: "Check if required variables are set"
  assert:
    that:
      - (nginx_vhost_user is defined) and nginx_vhost_user
      - (nginx_vhost_www_path is defined) and nginx_vhost_www_path

- name: "Install, harden & configure Nginx web server (+ optional CloudFlare support)"
  include_tasks: "server/{{ task_file }}"
  with_items:
    - 01.server.yml
    - 02.dh.yml
    - 03.cloudflare-real-ip.yml
    - 04.sblam-blacklist.yml
    - 05.symlink-support.yml
    - 99.env-variables.yml
  loop_control:
    loop_var: task_file

- name: "Configure Nginx to easily handle vhosts"
  include_tasks: "vhost/{{ task_file }}"
  with_items:
    - 01.owner-directories.yml
    - 02.shared-config.yml
    - 03.vhost-error-page.yml
    - 04.vhost-favicon.yml
    - 99.env-variables.yml
  loop_control:
    loop_var: task_file
