---

- name: "NGINX | SERVER | Remove Apache web server packages"
  yum:
    name: "{{ nginx_wv_packages_to_remove }}"
    state: removed

- name: "NGINX | SERVER | Hide some fastcgi params to be more secure"
  lineinfile:
    path: /etc/nginx/fastcgi.conf
    regexp: "{{ item }}"
    state: absent
  with_items:
    - '^fastcgi_param\s+GATEWAY_INTERFACE'
    - '^fastcgi_param\s+SERVER_SOFTWARE'

- name: "NGINX | SERVER | Remove Apache & Nginx leftovers"
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ nginx_wv_paths_to_remove }}"

- name: "NGINX | SERVER | Set 'client_body_buffer_size' value"
  replace:
    path: "{{ nginx_conf_file_path }}"
    regexp: "client_body_buffer_size 1k;"
    replace: "client_body_buffer_size {{ nginx_client_body_buffer_size }};"

- name: "NGINX | SERVER | Set modern SSL config (+ CloudFlare integration)"
  template:
    src: ssl.conf
    dest: "{{ nginx_conf_path }}/"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx
