---

- name: "NGINX | SERVER | Set system-wide environment variables for later use"
  lineinfile:
    path: /etc/environment
    line: 'export {{ item.key }}="{{ item.value }}"'
    owner: root
    group: root
    mode: "u=rw,go=r"
  with_items:
    - { "key": "NGINX_CONF_PATH", "value": "{{ nginx_conf_path }}" }
    - { "key": "NGINX_CONF_FILE_PATH", "value": "{{ nginx_conf_file_path }}" }
    - { "key": "NGINX_USER", "value": "{{ nginx_user }}" }
