---

- name: "NGINX | VHOST | Create www data user"
  user:
    name: "{{ nginx_vhost_user }}"
    password: !
    home: "{{ nginx_vhost_www_path }}"
    groups: "{{ ssh_allow_groups }}"
    append: true
    shell: /bin/bash
    state: present
  register: nginx_vhost_user_created

- name: "NGINX | VHOST | Add authorized SSH key to www data user"  # noqa 503
  authorized_key:
    user: "{{ nginx_vhost_user }}"
    key: "{{ lookup('file', nginx_vhost_user_ssh_key) }}"
    exclusive: true
  when: nginx_vhost_user_created.changed

- name: "NGINX | VHOST | Create vhost owner directories"
  file:
    name: "{{ nginx_vhost_domain_store_path }}"
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_vhost_user }}"
    mode: "ug=rwx,o=rx"
  with_items:
    - "{{ nginx_vhost_definition_conf_path }}"
    - "{{ nginx_vhost_domain_store_path }}"

- name: "NGINX | VHOST | Add vhosts config path to main nginx.conf"
  lineinfile:
    dest: /etc/nginx/nginx.conf
    insertafter: '\s+include {{ nginx_conf_path }}/\*\.conf;$'
    line: '    include {{ nginx_vhost_definition_conf_path }}/*.conf;'
    state: present
  notify: reload nginx

- name: "NGINX | VHOST | chown & chmod vhost home dir"
  file:
    name: "{{ nginx_vhost_www_path }}"
    state: directory
    owner: "{{ nginx_vhost_user }}"
    group: "{{ nginx_vhost_user }}"
    mode: "u=rwx,og=rx"
    force: true

- name: "NGINX | VHOST | Set the SELinux security context"  # noqa 305
  shell: "chcon -Rt {{ item.context }} {{ item.path }}"
  with_items:
    - { path: "{{ nginx_vhost_www_path }}", context: user_home_dir_t }
    - { path: "{{ nginx_vhost_www_path }}/.ssh }}", context: ssh_home_t }
    - { path: "{{ nginx_vhost_definition_conf_path }}", context: httpd_config_t }
    - { path: "{{ nginx_vhost_domain_store_path }}", context: httpd_sys_rw_content_t }
  when: ansible_selinux.status == "enabled"
